resources:
  - name: test
    type: GitRepo
    configuration:
      # SCM integration where the repository is located
      gitProvider: github # this will be replaced from values.yml
      # Repository path, including org name/repo name
      path: AvinashKomar/jfrog-workspace # this will be replaced from values.yml
      branches:
        # Specifies which branches will trigger dependent steps
        include: main

  - name: myBag
    type: PropertyBag
    configuration:
      commitSha: 1
      runID: 1
      
pipelines:

  - name: Frogbot_Scan_PR
    steps:
    - name: first
      type: Bash
      configuration:
        inputResources: 
          - name: test
      execution:
        onExecute:
          - echo "HELLO Avinash.. ONE!!"
          
    - name: second
      type: Bash
      configuration:
        requiresApproval: false
        inputSteps:
            - name: first
      execution:
        onExecute:
          - echo "HELLO Avinash.. TWO!!"
     

    - name: third
      type: Bash
      configuration:
        inputResources: 
          - name: test
      execution:
        onExecute:
          - echo "HELLO Avinash.. THREE!!"
