resources:
  - name: myFirstRepo
    type: GitRepo
    configuration:
      # SCM integration where the repository is located
      gitProvider: github # this will be replaced from values.yml
      # Repository path, including org name/repo name
      path: AvinashKomar/jfrog-workspace # this will be replaced from values.yml
      branches:
        # Specifies which branches will trigger dependent steps
        include: main
      cancelPendingRunsOn:
        newCommit: true

  - name: myBag
    type: PropertyBag
    configuration:
      commitSha: 1
      runID: 1
      
pipelines:

  - name: Mr_AviKom
    steps:
    - name: first
      type: Bash
      configuration:
        inputResources: 
          - name: myFirstRepo
      execution:
        onExecute:
          - echo "HELLO Avinash.. ONE!!"
          - add_run_variables x=2
          
    - name: second
      type: Bash
      configuration:
        inputSteps:
            - name: first
      execution:
        onExecute:
          - |
              if [ $x -eq 2 ]; then
                echo "$x is valid"
              else
                echo "$x is invalid"
              fi
      
        
    - name: third
      type: Bash
      configuration:
        inputResources: 
          - name: myFirstRepo
      execution:
        onExecute:
          - |
              status="IN_PROGRESS"
              i=1
              while [ "$status" == "IN_PROGRESS" ]; do
                echo "current status $status"
                i=$(( $i + 1 ))
                if [ $i -gt 5 ]; then
                  status="SUCCESS"
                fi
              done
